### ISSUE TITLE
启动时报错 似乎引用了一个不存在的模块

### ISSUE THREAD

**Issue by librationCrisis** [RShock/zhenxun_plugin_stock_legend#1]
![图片](https://user-images.githubusercontent.com/44491001/180386293-c8f5e611-1de7-4300-b118-6fd2e7d488b3.png)
版本 v1.6

**Comment by RShock** [comment]
请暂时将utils.py:line16的的from extensive_plugin.stock_legend .... 修改为 from .stock_model import StockDB
后续会随着1.7进行修复
