### ISSUE TITLE
[bug]清仓命令没有对躺平基金做特殊处理

### ISSUE THREAD

**Issue by Lu-Qi-777** [RShock/zhenxun_plugin_stock_legend#12]
https://github.com/RShock/zhenxun_plugin_stock_legend/blob/3a86ef56d21fbcdd5358ad426b3e007ded31c8b9/data_source.py#L191

把躺平基金当普通股票卖掉啦！收益没了←_←

**Comment by RShock** [comment]
正在修改

**Comment by RShock** [comment]
简单修了一下应该好了
