### ISSUE TITLE
No module named 'pymdownx'

### ISSUE THREAD

**Issue by SecretLoved** [RShock/zhenxun_plugin_stock_legend#15]
![image](https://user-images.githubusercontent.com/73172198/188180873-8080f125-6b3f-448a-89a1-c6e28b334b9a.png)

**Comment by RShock** [comment]
参考readme 最下面

**Comment by SecretLoved** [comment]
![image](https://user-images.githubusercontent.com/73172198/188197911-4fd8911f-7d39-4859-8e85-3c976e49c062.png)
仍然出现此问题
![image](https://user-images.githubusercontent.com/73172198/188198070-7cd138d1-6952-45e0-b13a-ddb82ee202b7.png)

**Comment by RShock** [comment]
尝试安装 pymdown-extensions

**Comment by SecretLoved** [comment]
![image](https://user-images.githubusercontent.com/73172198/188199685-fffb4002-e028-417a-8b5c-aa7ceaeee9e7.png)
报错变为
![image](https://user-images.githubusercontent.com/73172198/188199710-3438ae8f-da93-4fb4-9862-34e306ad2a38.png)

**Comment by RShock** [comment]
尝试安装 python-markdown-math

**Comment by SecretLoved** [comment]
问题已解决，感谢
