### ISSUE TITLE
更新插件出现报错

### ISSUE THREAD

**Issue by PackageInstaller** [RShock/zhenxun_plugin_stock_legend#18]
从v1.9更新到最新的2.4,然后就报错了
![Screenshot_20230116_163353](https://user-images.githubusercontent.com/80018096/212634413-01faab3b-ba97-4ff5-9e45-3171f3953ccc.png)

**Comment by RShock** [comment]
可能是我在1.9之后改动了数据库属性。

尝试在https://github.com/RShock/zhenxun_plugin_stock_legend/blob/main/stock_model.py 的第9行添加
```
_table_args__ = {'extend_existing': True}
```

在做这个操作之前，请对数据库做好备份防止意外。

**Comment by PackageInstaller** [comment]
感谢！！！
