### ISSUE TITLE
请求适配真寻新版本

### ISSUE THREAD

**Issue by CCYellowStar** [RShock/zhenxun_plugin_stock_legend#19]

**Comment by PackageInstaller** [comment]
+1

**Comment by RShock** [comment]
尝试进行了适配，但是一半都是chatgpt帮我写的，可以先测试看看有没有什么问题
新数据库强行要求decimal但是我没有从头做适配，反而使插件精度轻微降低了。

**Comment by CCYellowStar** [comment]
呜呜会有时区问题<class 'tortoise.exceptions.OperationalError'>: invalid input for query argument $4: datetime.datetime(2023, 3, 16, 7, 2, 25,... (can't subtract offset-naive and offset-aware datetimes)

**Comment by PackageInstaller** [comment]
我遇到的是data value time out什麼的
这个报错是由于时间戳超出了 Python 所支持的时间范围，导致时间值超出了系统所能表示的范围而引发的。具体可以参考报错信息中的最后一行：`date value out of range`。

根据报错信息可以看到，这个问题是在 `tortoise/timezone.py` 这个文件中的 `make_aware` 方法中引发的，这个方法将时间戳转换为带时区的时间，并返回一个带时区的日期时间对象。在转换中，使用了 `tz.localize(value, is_dst=is_dst)` 这个方法，对时间进行本地化处理，从而把一个 UTC 时间转换成了本地时区的日期时间对象。但是，由于时间戳超出了系统所支持的范围，导致时间值超出了系统的表示范围，所以在转换过程中引发了 OverflowError。

要解决这个问题，可以尝试使用其他更高精度的时间库，比如 datetime，或者使用其他处理超出时间范围的方法，比如使用字符串表示时间戳等。同时，如果可能的话，也可以考虑使用更小的时间戳值，以避免超出系统所支持的时间范围。

**Comment by RShock** [comment]
看起来，旧数据的datetime格式和新版在时区设定这方面有着微妙的不同。
如果删除旧表的话是可以正常创建的。

尝试执行以下sql
```
alter table public.stock_game alter column buy_time type timestamp with time zone using buy_time::timestamp with time zone;
```
如果在真寻中，可以在qq利用真寻自己的exec指令直接执行
```
@真寻 exec alter table public.stock_game alter column buy_time type timestamp with time zone using buy_time::timestamp with time zone;
```
在buy_time列的类型变成timestamp with time zone之后，问题应该会消失。

**Comment by CCYellowStar** [comment]
可以了

**Comment by CCYellowStar** [comment]
卖股票它显示结果会报错，在data_source151行要转float
