### ISSUE TITLE
使用我的持仓和查看持仓时报错

### ISSUE THREAD

**Issue by librationCrisis** [RShock/zhenxun_plugin_stock_legend#2]
![图片](https://user-images.githubusercontent.com/44491001/180400758-1dfbbcd0-732c-4804-bcff-ce1d2b6410c6.png)
版本v1.6 已在虚拟环境安装markdown

**Comment by librationCrisis** [comment]
其实我想问一下真的有pymdownx这个模块吗
![图片](https://user-images.githubusercontent.com/44491001/180409588-0e656bd4-4581-4673-8ab5-02843a634226.png)

**Comment by RShock** [comment]
并没有，看起来这是markdown自己的模块
你可以尝试install以下3个插件
mkdocs 
mkdocs-marterial 
pymdown-extensions

**Comment by RShock** [comment]
已经更新到1.7
适配代码`fit=False`代码被移动到了配置文件当中，需要运行一次新插件后，到配置文件里面配好

**Comment by RShock** [comment]
先别更 我代码里忘记扣钱了

**Comment by RShock** [comment]
这部分代码比我想的复杂，我再处理一下

**Comment by RShock** [comment]
大概好了

**Comment by mmmjie** [comment]
> 这个问题会麻烦一点，因为`nonebot_plugin_htmlrender`是一个很难搞的插件，我是没搞清楚的。尤其是windows下问题多多（虽然看起来你这个好像不是windws） 你可以尝试先
> 
> ```
> pip install nonebot_plugin_htmlrender
> ```
> 
> 以及
> 
> ```
> pip install pymdownx
> ```
> 
> 等等方法尝试解决（如果使用虚拟环境则使用`poetry add pymdownx`等）这类指令 同时在`.env.dev`加上一行
> 
> ```
> FASTAPI_RELOAD=false
> ```
> 
> 但是老实说这些方法都是我胡乱搞的，大概都没什么用
> 
> 最终方案是，`__init.py__`里比较靠前的地方有一行`fit = False`改成`fit = True`
> 
> 这会牺牲一点风控防范能力，但是能保证功能正常运行

我按照前几部操作好了，没有使用最终方案，感谢！

**Comment by librationCrisis** [comment]
问题已解决 除了安装 `mkdocs` `mkdocs-material`上面打多了个r 和`pymdown-extensions`之外 还需要安装`python-markdown-math`
