### ISSUE TITLE
插件载入时报错

### ISSUE THREAD

**Issue by yuan488** [RShock/zhenxun_plugin_stock_legend#20]
`cannot import name 'db' from 'services.db_context' (D:\bot\zhenxun_bot\services\db_context.py)`

**Comment by idonotthinksoso** [comment]
同样的问题，应该是数据库舍弃gino使用tortoise的原因，求佬配适。

**Comment by RShock** [comment]
在做了.jpg

**Comment by RShock** [comment]
尝试进行了适配，但是一半都是chatgpt帮我写的，可以先测试看看有没有什么问题
新数据库强行要求decimal但是我没有从头做适配，反而使插件精度轻微降低了。

**Comment by idonotthinksoso** [comment]
> 尝试进行了适配，但是一半都是chatgpt帮我写的，可以先测试看看有没有什么问题 新数据库强行要求decimal但是我没有从头做适配，反而使插件精度轻微降低了。

佬, 买卖股票有bug, 金币消失了,但是我的持仓没有显示买入的股票. 想卖出显示没有买入此股票

**Comment by RShock** [comment]
参考#19 另外金币只能你自己手动加一下了

**Comment by idonotthinksoso** [comment]
> 参考#19 另外金币只能你自己手动加一下了

ok了, 谢谢佬
