### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by PackageInstaller** [RShock/zhenxun_plugin_stock_legend#21]
我的持仓报错
![Screenshot_20230317_180226](https://user-images.githubusercontent.com/80018096/225874962-b42f969a-a98f-45bf-9a0c-1ed4b6dd6fb8.png)

买入股票报错
![Screenshot_20230317_180326](https://user-images.githubusercontent.com/80018096/225875060-82b6a39e-66c2-4197-8425-104df70572e0.png)

数据库stock_game内部分截图
![Screenshot_20230317_180603](https://user-images.githubusercontent.com/80018096/225875150-961dd3a1-ecdc-434f-9a54-856277c5224c.png)

**Comment by PackageInstaller** [comment]
用git clone下载的最新插件

**Comment by RShock** [comment]
已尝试修复
