### ISSUE TITLE
购置基金时，无法截取网页截图

### ISSUE THREAD

**Issue by xiaorui158** [RShock/zhenxun_plugin_stock_legend#3]
![image](https://user-images.githubusercontent.com/88604496/180783966-88f89db3-91ff-4d88-a6d6-f4d835e9b090.png)
佬把这部分改一下，还有我想问一下这个网页截图有开发文档吗，有的图截取的太多了，我想去看看能不能指定截取区域。

**Comment by RShock** [comment]
截图从微博热搜插件抄的代码，而且我完全搞不懂。
因为让他截完整网页基本都能成功，但是对于大部分网页一旦指定元素截图，就一定失败。然后调整长宽的参数好像也完全不生效。我在各大股票网站都试了下只有百度股市通最正常。

**Comment by RShock** [comment]
读了一下代码，我逐渐理解一切
PlayWright是一个大型库所以教程还挺多的，大致上选择器可以参考这边
https://blog.csdn.net/Code_LT/article/details/120304894

**Comment by xiaorui158** [comment]
好的，感谢

**Comment by RShock** [comment]
新代码写了一些截图代码，放在release包里了
