### ISSUE TITLE
【需求】希望新增日股的买卖

### ISSUE THREAD

**Issue by mmmjie** [RShock/zhenxun_plugin_stock_legend#4]
个人感觉真寻用户的群体大部分都有玩日游；
在使用的时候，会有想购买日游运营公司的股票欲望；
所以希望新增日本股票的买卖。
另外如何将默认K线从分时改成日K呢？ 
                                                        

--------------------------------------感谢作者的分享！我的Q群成员很喜欢这个插件！

**Comment by RShock** [comment]
如果使用今天发布的release版，是使用同时显示分时和k线的改良图的
日股后续会考虑，但是最近至少7天我摸不到电脑
