### ISSUE TITLE
Jinja2 ? 是不是打错了

### ISSUE THREAD

**Issue by darkdokido** [RShock/zhenxun_plugin_stock_legend#7]

**Comment by RShock** [comment]
可能吧，但是我不记得正确的是什么。你可以运行之后看看缺什么再告诉我

**Comment by librationCrisis** [comment]
![图片](https://user-images.githubusercontent.com/44491001/182064419-452ca958-f146-4aa7-bfad-bd27ccb8e9e8.png)
打多了一个i

**Comment by RShock** [comment]
感谢提醒
