### ISSUE TITLE
躺平基金是不是有亿点点离谱了

### ISSUE THREAD

**Issue by librationCrisis** [RShock/zhenxun_plugin_stock_legend#9]
![图片](https://user-images.githubusercontent.com/44491001/182744732-a213b233-ce00-44c5-bcfd-2c025f314454.png)
![图片](https://user-images.githubusercontent.com/44491001/182744762-803028f2-a448-45ac-8672-5036e79f93b4.png)
版本v2.1

**Comment by librationCrisis** [comment]
![图片](https://user-images.githubusercontent.com/44491001/182745827-44263349-edc9-4e72-9dbb-c3fbbbc6979c.png)
配置文件里的确实是1.5%

**Comment by RShock** [comment]
懂了，这是因为我读的是`stock_legend`的配置文件，你这边是`zhenxun_plugin_stock_legend`导致的，实际上你这边的配置是全部失效的
我得看看怎么修

**Comment by RShock** [comment]
新版应该可以了
